import { Product, Material, Testimonial } from "./types";

export const PRODUCTS: Product[] = [
  // ==========================================
  // --- CATEGORY 1: SEATING (35 ITEMS) ---
  // ==========================================
  {
    id: "bar-stool-studio",
    product: "The Apex Bar Stool",
    price: "₦195,000",
    category: "seating",
    image: "/Bar_stool_in_studio_202607131956.jpeg",
    spec: "Handcrafted Iroko Wood & Black Steel Frame",
  },
  {
    id: "barrel-chair-studio",
    product: "The Solace Barrel Chair",
    price: "₦320,000",
    category: "seating",
    image: "/Barrel_chair_in_studio_202607131957.jpeg",
    spec: "Bouclé Fabric & Smoked Oak Base",
  },
  {
    id: "chaise-lounge-studio",
    product: "The Serenity Chaise Lounge",
    price: "₦580,000",
    category: "seating",
    image: "/Chaise_lounge_in_studio_202607131956.jpeg",
    spec: "Premium Velvet & Hand-polished Walnut",
  },
  {
    id: "club-chair-studio",
    product: "The Heritage Club Chair",
    price: "₦385,000",
    category: "seating",
    image: "/Club_chair_in_studio_202607131956.jpeg",
    spec: "Full-Grain Kano Leather & Aged Brass Accents",
  },
  {
    id: "designer-folding-chair-studio",
    product: "The Origami Folding Chair",
    price: "₦120,000",
    category: "seating",
    image: "/Designer_wooden_folding_chair_st_202607131956.jpeg",
    spec: "Sculpted Ash Wood & Solid Brass Hinges",
  },
  {
    id: "directors-chair-studio",
    product: "The Director's Accent Chair",
    price: "₦260,000",
    category: "seating",
    image: "/Directors_chair_in_studio_202607131956.jpeg",
    spec: "Premium Canvas & Ebonized Mahogany Frame",
  },
  {
    id: "ergonomic-office-chair-studio",
    product: "The Apex Ergonomic Chair",
    price: "₦340,000",
    category: "seating",
    image: "/Ergonomic_office_chair_studio_202607131956.jpeg",
    spec: "Molded Birch Plywood & Mesh Support",
  },
  {
    id: "folding-chair-studio",
    product: "The Minimalist Folding Chair",
    price: "₦95,000",
    category: "seating",
    image: "/Folding_chair_in_studio_202607131956.jpeg",
    spec: "Natural Teak & Brushed Steel Accent",
  },
  {
    id: "handcrafted-armchair-studio",
    product: "The Artisan Accent Armchair",
    price: "₦290,000",
    category: "seating",
    image: "/Handcrafted_wooden_armchair_studio_202607131956.jpeg",
    spec: "Solid Iroko Wood & Hand-woven Rattan Seat",
  },
  {
    id: "papasan-chair-studio",
    product: "The Cloud Papasan Chair",
    price: "₦280,000",
    category: "seating",
    image: "/Papasan_chair_in_studio_202607131956.jpeg",
    spec: "Cured Bamboo Frame & Raw Linen Cushion",
  },
  {
    id: "scandinavian-stool-studio",
    product: "The Oslo Ash Stool",
    price: "₦110,000",
    category: "seating",
    image: "/Scandinavian_stool_in_studio_202607131956.jpeg",
    spec: "Scandinavian Ash Wood & Matte Lacquer Finish",
  },
  {
    id: "sleek-leather-sofa-studio",
    product: "The Horizon Leather Sofa",
    price: "₦1,850,000",
    category: "seating",
    image: "/Sleek_leather_sofa_studio_202607131956.jpeg",
    spec: "Full-grain Cordovan Leather & Steel Beam Support",
  },
  {
    id: "sofa-frame-cushions-studio",
    product: "The Lagos Lounge Sofa",
    price: "₦1,450,000",
    category: "seating",
    image: "/Sofa_frame_with_cushions_studio_202607131957.jpeg",
    spec: "Smoked Oak Frame & Belgian Linen Cushions",
  },
  {
    id: "task-chair-studio",
    product: "The Atelier Task Chair",
    price: "₦210,000",
    category: "seating",
    image: "/Task_chair_in_studio_202607131956.jpeg",
    spec: "Molded Walnut Shell & Full-grain Leather",
  },
  {
    id: "velvet-loveseat-studio",
    product: "The Imperial Velvet Loveseat",
    price: "₦920,000",
    category: "seating",
    image: "/Velvet_loveseat_in_studio_202607131957.jpeg",
    spec: "Plush Royal Velvet & Gilded Brass Legs",
  },
  {
    id: "wingback-chair-studio",
    product: "The Grand Wingback Chair",
    price: "₦460,000",
    category: "seating",
    image: "/Wingback_chair_in_studio_202607131956.jpeg",
    spec: "Hand-stitched Tweed & Mahogany Carved Legs",
  },
  {
    id: "wooden-bar-stool-studio",
    product: "The Classic Bar Stool",
    price: "₦135,000",
    category: "seating",
    image: "/Wooden_bar_stool_studio_photography_202607131956.jpeg",
    spec: "Natural Mahogany Wood & Iron Footrest",
  },
  {
    id: "wooden-deck-chair-studio",
    product: "The Riviera Deck Chair",
    price: "₦180,000",
    category: "seating",
    image: "/Wooden_deck_chair_studio_photogr_202607131956.jpeg",
    spec: "Teak & Weatherproof Sailcloth Sling",
  },
  {
    id: "wooden-dining-chair-studio",
    product: "The Monarch Dining Chair",
    price: "₦165,000",
    category: "seating",
    image: "/Wooden_dining_chair_studio_202607131956.jpeg",
    spec: "Smoked Walnut Wood & Slim Profile Frame",
  },
  {
    id: "wooden-lounge-chair-studio-1",
    product: "The Architect Lounge Chair (Angle 1)",
    price: "₦520,000",
    category: "seating",
    image: "/Wooden_lounge_chair_studio_202607131956.jpeg",
    spec: "Sculpted Rosewood & Cordovan Leather Seat",
  },
  {
    id: "wooden-lounge-chair-studio-2",
    product: "The Architect Lounge Chair (Angle 2)",
    price: "₦520,000",
    category: "seating",
    image: "/Wooden_lounge_chair_studio_202607131956_2.jpeg",
    spec: "Sculpted Rosewood & Cordovan Leather Seat",
  },
  {
    id: "wooden-lounge-chair-studio-3",
    product: "The Architect Lounge Chair (Angle 3)",
    price: "₦520,000",
    category: "seating",
    image: "/Wooden_lounge_chair_studio_202607131956_3.jpeg",
    spec: "Sculpted Rosewood & Cordovan Leather Seat",
  },
  {
    id: "wooden-rocking-chair-studio",
    product: "The Heritage Rocking Chair",
    price: "₦240,000",
    category: "seating",
    image: "/Wooden_rocking_chair_studio_phot_202607131956.jpeg",
    spec: "Cured Mahogany & Ergonomic Spine Support",
  },
  {
    id: "wooden-side-chair-studio",
    product: "The Lineage Side Chair",
    price: "₦145,000",
    category: "seating",
    image: "/Wooden_side_chair_studio_photogr_202607131956.jpeg",
    spec: "African Walnut & Floating Joinery",
  },
  {
    id: "woven-wicker-chair-studio",
    product: "The Woven Wicker Accent Chair",
    price: "₦220,000",
    category: "seating",
    image: "/Woven_wicker_chair_studio_202607131957.jpeg",
    spec: "Natural Rattan & Ash Wood Frame",
  },
  // UNSPLASH SEATING (10 ITEMS)
  {
    id: "horizon-lounge-unsplash",
    product: "The Horizon Lounge Sofa",
    price: "₦1,650,000",
    category: "seating",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800",
    spec: "Premium Linen & Hardwood Sub-Frame",
  },
  {
    id: "alto-bar-stool-unsplash",
    product: "The Alto Leather Stool",
    price: "₦180,000",
    category: "seating",
    image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?q=80&w=800",
    spec: "Aged Brass & Full-Grain Leather",
  },
  {
    id: "meridian-chair-unsplash",
    product: "The Meridian Accent Chair",
    price: "₦290,000",
    category: "seating",
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=800",
    spec: "Sculpted Ash Wood & Woven Seat",
  },
  {
    id: "solace-lounge-unsplash",
    product: "The Solace Lounge Chair",
    price: "₦262,000",
    category: "seating",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800",
    spec: "Smoked Walnut & Brass Joint Elements",
  },
  {
    id: "cascade-ottoman-unsplash",
    product: "The Cascade Ottoman",
    price: "₦181,000",
    category: "seating",
    image: "https://images.unsplash.com/photo-1503602642458-232111445657?q=80&w=800",
    spec: "Aged Brass & Full-Grain Leather Trim",
  },
  {
    id: "nova-armchair-unsplash",
    product: "The Nova Armchair",
    price: "₦1,114,000",
    category: "seating",
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=800",
    spec: "Smoked Walnut & Solid Brass Details",
  },
  {
    id: "velvet-armchair-unsplash-extra",
    product: "The Velvet Lounge Armchair",
    price: "₦380,000",
    category: "seating",
    image: "https://images.unsplash.com/photo-1549497538-30122d48f578?q=80&w=800",
    spec: "Sculpted Timber Frame & Sage Velvet Cushioning",
  },
  {
    id: "scandi-lounge-unsplash-extra",
    product: "The Oslo Easy Chair",
    price: "₦310,000",
    category: "seating",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?q=80&w=800",
    spec: "Scandinavian Bentwood & Organic Wool Upholstery",
  },
  {
    id: "steel-lounge-unsplash-extra",
    product: "The Bauhaus Suspension Chair",
    price: "₦440,000",
    category: "seating",
    image: "https://images.unsplash.com/photo-1517806428044-7153b27654ac?q=80&w=800",
    spec: "Cantilever Tubular Steel & Saddle Leather",
  },
  {
    id: "woven-accent-unsplash-extra",
    product: "The Woven Atelier Armchair",
    price: "₦265,000",
    category: "seating",
    image: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?q=80&w=800",
    spec: "Solid Oak & Braided Hemp Cord Seat",
  },

  // ==========================================
  // --- CATEGORY 2: TABLES (26 ITEMS) ---
  // ==========================================
  {
    id: "birch-wood-coffee-table-studio",
    product: "The Birch Storage Coffee Table",
    price: "₦390,000",
    category: "tables",
    image: "/Birch_wood_coffee_table_storage_202607131957.jpeg",
    spec: "Cured Birch Wood & Fluted Glass Storage Drawer",
  },
  {
    id: "cherry-wood-end-table-studio",
    product: "The Cherry Wood Side Table",
    price: "₦180,000",
    category: "tables",
    image: "/Cherry_wood_end_table_studio_202607131956.jpeg",
    spec: "Aged Cherry Wood & Brass Ring Pull",
  },
  {
    id: "mahogany-wood-meeting-table-studio",
    product: "The Executive Boardroom Table",
    price: "₦1,850,000",
    category: "tables",
    image: "/Mahogany_wood_meeting_table_studio_202607131956.jpeg",
    spec: "Solid African Mahogany & Polished Brass Inlays",
  },
  {
    id: "nesting-wooden-coffee-tables-studio",
    product: "The Duo Nesting Coffee Tables",
    price: "₦310,000",
    category: "tables",
    image: "/Nesting_wooden_coffee_tables_studio_202607131956.jpeg",
    spec: "Two-Tier Smoked Walnut & Ash Duo",
  },
  {
    id: "oval-wooden-dining-table-studio",
    product: "The Zenith Oval Dining Table",
    price: "₦1,150,000",
    category: "tables",
    image: "/Oval_wooden_dining_table_studio_202607131956.jpeg",
    spec: "Sculpted Rosewood & Solid Pedestal Base",
  },
  {
    id: "round-dining-table-studio",
    product: "The Eclipse Round Dining Table",
    price: "₦850,000",
    category: "tables",
    image: "/Round_dining_table_studio_202607131957.jpeg",
    spec: "Ebonized Oak & Brushed Copper Base",
  },
  {
    id: "scandinavian-ash-wood-dining-table-studio",
    product: "The Scandinavian Ash Dining Table",
    price: "₦950,000",
    category: "tables",
    image: "/Scandinavian_ash_wood_dining_table_202607131957.jpeg",
    spec: "White Ash Wood & Mortise-and-Tenon Joints",
  },
  {
    id: "teak-wood-bistro-table-studio",
    product: "The Bistro Teak Table",
    price: "₦260,000",
    category: "tables",
    image: "/Teak_wood_bistro_table_studio_202607131956.jpeg",
    spec: "Bespoke Cured Teak & Cast Iron Pedestal",
  },
  {
    id: "walnut-coffee-table-studio",
    product: "The Grand Walnut Coffee Table",
    price: "₦410,000",
    category: "tables",
    image: "/Walnut_coffee_table_studio_photo_202607131957.jpeg",
    spec: "Smoked Black Walnut & Gilded Joints",
  },
  {
    id: "wood-iron-sofa-table-studio",
    product: "The Industrial Console Table",
    price: "₦290,000",
    category: "tables",
    image: "/Wood_iron_sofa_table_studio_202607131957.jpeg",
    spec: "Reclaimed Wood & Structural Steel Frame",
  },
  {
    id: "wooden-accent-table-tree-stump-studio",
    product: "The Organic Stump Accent Table",
    price: "₦150,000",
    category: "tables",
    image: "/Wooden_accent_table_tree_stump_202607131957.jpeg",
    spec: "Sustainably Harvested Iroko Wood Stump",
  },
  {
    id: "wooden-bar-height-table-studio",
    product: "The High-Top Trestle Bar Table",
    price: "₦480,000",
    category: "tables",
    image: "/Wooden_bar-height_table_studio_202607131957.jpeg",
    spec: "African Mahogany Wood & Brass Footrest Bar",
  },
  {
    id: "wooden-coffee-table-metal-legs-studio",
    product: "The Minimalist Coffee Table",
    price: "₦240,000",
    category: "tables",
    image: "/Wooden_coffee_table_metal_legs_202607131957.jpeg",
    spec: "Cured Birch & Matte Black Steel V-Legs",
  },
  {
    id: "wooden-coffee-table-studio",
    product: "The Classic Coffee Table",
    price: "₦280,000",
    category: "tables",
    image: "/Wooden_coffee_table_studio_202607131956.jpeg",
    spec: "Solid Iroko Wood & Tapered Peg Legs",
  },
  {
    id: "wooden-hallway-console-table-studio",
    product: "The Hallway Credenza Table",
    price: "₦360,000",
    category: "tables",
    image: "/Wooden_hallway_console_table_studio_202607131956.jpeg",
    spec: "African Walnut & Fluted Glass Front Drawers",
  },
  {
    id: "wooden-pedestal-side-table-studio",
    product: "The Pedestal Accent Side Table",
    price: "₦165,000",
    category: "tables",
    image: "/Wooden_pedestal_side_table_studio_202607131956.jpeg",
    spec: "Turned Ash Wood & Satin Lacquer Finish",
  },
  {
    id: "wooden-side-table-studio",
    product: "The Handcrafted End Table",
    price: "₦195,000",
    category: "tables",
    image: "/Wooden_side_table_studio_photogr_202607131956.jpeg",
    spec: "African Walnut Wood & Floating Joinery Detail",
  },
  {
    id: "wooden-trestle-dining-table-studio",
    product: "The Grand Trestle Dining Table",
    price: "₦1,380,000",
    category: "tables",
    image: "/Wooden_trestle_dining_table_studio_202607131956.jpeg",
    spec: "10-Seater Cured Teak & Architectural Trestle Base",
  },
  // UNSPLASH TABLES (8 ITEMS)
  {
    id: "monarch-dining-unsplash",
    product: "The Monarch Dining Table",
    price: "₦1,250,000",
    category: "tables",
    image: "https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?q=80&w=800",
    spec: "Smoked Walnut & Aged Brass Accents",
  },
  {
    id: "orbit-coffee-unsplash",
    product: "The Orbit Coffee Table",
    price: "₦240,000",
    category: "tables",
    image: "https://images.unsplash.com/photo-1581428982868-e410dd047a90?q=80&w=800",
    spec: "Raw Concrete & Walnut Top",
  },
  {
    id: "ethereal-coffee-unsplash",
    product: "The Ethereal Coffee Table",
    price: "₦337,000",
    category: "tables",
    image: "https://images.unsplash.com/photo-1604014237800-1c9102c219da?q=80&w=800",
    spec: "Sculpted Ash Wood & Woven Base",
  },
  {
    id: "zenith-coffee-unsplash",
    product: "The Zenith Coffee Table",
    price: "₦569,000",
    category: "tables",
    image: "https://images.unsplash.com/photo-1577140917170-285929ef55af?q=80&w=800",
    spec: "Iroko Wood & Matte Black Steel Crossbars",
  },
  {
    id: "aether-coffee-unsplash",
    product: "The Aether Coffee Table",
    price: "₦530,000",
    category: "tables",
    image: "https://images.unsplash.com/photo-1530018607912-ef56df760738?q=80&w=800",
    spec: "Bespoke Travertine & Ash Frame",
  },
  {
    id: "travertine-coffee-unsplash-extra",
    product: "The Travertine Horizon Coffee Table",
    price: "₦465,000",
    category: "tables",
    image: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=800",
    spec: "Honed Travertine Slab & Brushed Bronze Pedestals",
  },
  {
    id: "walnut-dining-unsplash-extra",
    product: "The Walnut Cathedral Dining Table",
    price: "₦1,420,000",
    category: "tables",
    image: "https://images.unsplash.com/photo-1604578762246-411356547ec1?q=80&w=800",
    spec: "Smoked French Walnut & Architectural Column Base",
  },
  {
    id: "nordic-dining-unsplash-extra",
    product: "The Stockholm Dining Table",
    price: "₦1,050,000",
    category: "tables",
    image: "https://images.unsplash.com/photo-1577140917170-285929ef55af?q=80&w=800",
    spec: "Bleached Scandinavian Ash & Trestle Geometry",
  },

  // ==========================================
  // --- CATEGORY 3: BEDROOM (12 ITEMS) ---
  // ==========================================
  {
    id: "wooden-headboard-studio",
    product: "The Fluted Headboard Panel",
    price: "₦380,000",
    category: "bedroom",
    image: "/Wooden_headboard_in_studio_202607131956.jpeg",
    spec: "African Mahogany Wood & Integrated LED Channels",
  },
  {
    id: "wooden-king-size-bed-frame-studio",
    product: "The Monarch King Bed Frame",
    price: "₦950,000",
    category: "bedroom",
    image: "/Wooden_king-size_bed_frame_202607131957.jpeg",
    spec: "Solid Rosewood & Premium Ivory Bouclé Upholstered Headboard",
  },
  {
    id: "wooden-nightstands-studio",
    product: "The Floating Nightstands Duo",
    price: "₦280,000",
    category: "bedroom",
    image: "/Wooden_nightstands_in_studio_202607131957.jpeg",
    spec: "Handcrafted Iroko Wood & Soft-Close Drawers",
  },
  {
    id: "wooden-platform-bed-frame-studio",
    product: "The Minimalist Platform Bed Frame",
    price: "₦780,000",
    category: "bedroom",
    image: "/Wooden_platform_bed_frame_studio_202607131956.jpeg",
    spec: "Solid White Oak & Low Profile Japanese Frame Style",
  },
  {
    id: "wooden-dresser-studio",
    product: "The Artisan Six-Drawer Dresser",
    price: "₦650,000",
    category: "bedroom",
    image: "/Wooden_dresser_in_studio_202607131956.jpeg",
    spec: "African Mahogany & Brushed Bronze Hardware",
  },
  // UNSPLASH BEDROOM (7 ITEMS)
  {
    id: "haven-bed-unsplash",
    product: "The Haven Platform Bed",
    price: "₦950,000",
    category: "bedroom",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=800",
    spec: "Teak & Ivory Bouclé Upholstery",
  },
  {
    id: "meridian-dresser-unsplash",
    product: "The Meridian Dresser",
    price: "₦168,000",
    category: "bedroom",
    image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=800",
    spec: "African Mahogany & Fluted Glass Doors",
  },
  {
    id: "paramount-dresser-unsplash",
    product: "The Paramount Dresser",
    price: "₦745,000",
    category: "bedroom",
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=800",
    spec: "Ebonized Oak & Polished Nickel Elements",
  },
  {
    id: "aura-dresser-unsplash",
    product: "The Aura Dresser",
    price: "₦950,000",
    category: "bedroom",
    image: "https://images.unsplash.com/photo-1505693314120-0d443864aa7a?q=80&w=800",
    spec: "African Mahogany & Fluted Glass Facade",
  },
  {
    id: "wooden-headboard-unsplash-extra",
    product: "The Serenity Canopy Bed",
    price: "₦1,180,000",
    category: "bedroom",
    image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=800",
    spec: "Cured Mahogany poster canopy frame with satin wax finish",
  },
  {
    id: "bedside-lamp-unsplash-extra",
    product: "The Horizon Bedside Pedestal",
    price: "₦210,000",
    category: "bedroom",
    image: "https://images.unsplash.com/photo-1617806118233-18e1db207f62?q=80&w=800",
    spec: "Single drawer walnut stand with integrated brass charging plate",
  },
  {
    id: "mid-century-credenza-unsplash-extra",
    product: "The Stockholm Low Sideboard",
    price: "₦690,000",
    category: "bedroom",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=800",
    spec: "Mid-Century Ash veneer frame & tapered dowel legs",
  },

  // ==========================================
  // --- CATEGORY 4: OFFICE (11 ITEMS) ---
  // ==========================================
  {
    id: "oak-executive-desk-studio",
    product: "The Grand Executive Oak Desk",
    price: "₦1,120,000",
    category: "office",
    image: "/Oak_executive_desk_studio_202607131957.jpeg",
    spec: "Solid White Oak & Leather Inlay Writing Pad",
  },
  {
    id: "wooden-credenza-for-office-storage-studio",
    product: "The Office Storage Credenza",
    price: "₦580,000",
    category: "office",
    image: "/Wooden_credenza_for_office_storage_202607131957.jpeg",
    spec: "Ebonized Oak & Integrated Cord Channels",
  },
  {
    id: "wooden-two-drawer-filing-cabinet-studio",
    product: "The Two-Drawer Filing Cabinet",
    price: "₦240,000",
    category: "office",
    image: "/Wooden_two-drawer_filing_cabinet_202607131957.jpeg",
    spec: "Smoked Walnut Wood & Heavy Duty Steel Glides",
  },
  {
    id: "wooden-rolling-file-cart-studio",
    product: "The Rolling Archive Cart",
    price: "₦180,000",
    category: "office",
    image: "/Wooden_rolling_file_cart_studio_202607131956.jpeg",
    spec: "Birch Plywood & Lockable Industrial Casters",
  },
  {
    id: "wooden-laptop-stand-studio",
    product: "The Ergonomic Laptop Stand",
    price: "₦65,000",
    category: "office",
    image: "/Wooden_laptop_stand_studio_202607131956.jpeg",
    spec: "Molded Walnut Veneer & Anti-Slip Base",
  },
  {
    id: "wooden-printer-stand-studio",
    product: "The Office Printer Stand",
    price: "₦155,000",
    category: "office",
    image: "/Wooden_printer_stand_studio_202607131956.jpeg",
    spec: "Solid Ash Wood & Heavy Duty Leveling Feet",
  },
  // UNSPLASH OFFICE (5 ITEMS)
  {
    id: "prestige-desk-unsplash",
    product: "The Prestige Writing Desk",
    price: "₦580,000",
    category: "office",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?q=80&w=800",
    spec: "African Mahogany & Steel Support",
  },
  {
    id: "obsidian-cabinet-unsplash",
    product: "The Obsidian Filing Cabinet",
    price: "₦1,097,000",
    category: "office",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800",
    spec: "Teak & Ivory Bouclé Upholstery Panels",
  },
  {
    id: "summit-cabinet-unsplash",
    product: "The Summit Filing Cabinet",
    price: "₦674,000",
    category: "office",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800",
    spec: "Carrara Marble & Gunmetal Rails",
  },
  {
    id: "echo-cabinet-unsplash",
    product: "The Echo Filing Cabinet",
    price: "₦353,000",
    category: "office",
    image: "https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?q=80&w=800",
    spec: "Teak & Ivory Bouclé Upholstered Drawer Fronts",
  },
  {
    id: "workspace-oak-unsplash-extra",
    product: "The Architect Studio Desk",
    price: "₦820,000",
    category: "office",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800",
    spec: "Ebonized ash top frame & solid structural iron legs",
  },

  // ==========================================
  // --- CATEGORY 5: CUSTOM & ACCENTS (39 ITEMS) ---
  // ==========================================
  {
    id: "handcrafted-wooden-library-ladder-studio",
    product: "The Library Ladder",
    price: "₦280,000",
    category: "custom",
    image: "/Handcrafted_wooden_library_ladde_202607131956.jpeg",
    spec: "Solid Oak Frame & Brass Roller Hardware",
  },
  {
    id: "handcrafted-wooden-room-divider-studio",
    product: "The Modernist Room Divider",
    price: "₦420,000",
    category: "custom",
    image: "/Handcrafted_wooden_room_divider_202607131957.jpeg",
    spec: "Slatted Teak Panel Architecture",
  },
  {
    id: "handcrafted-wooden-screen-studio",
    product: "The Custom Slatted Screen",
    price: "₦390,000",
    category: "custom",
    image: "/Handcrafted_wooden_screen_studio_202607131957.jpeg",
    spec: "Ebonized Ash & Gilded Brass Details",
  },
  {
    id: "handcrafted-wooden-wine-rack-studio",
    product: "The Bespoke Wine Rack",
    price: "₦260,000",
    category: "custom",
    image: "/Handcrafted_wooden_wine_rack_studio_202607131956.jpeg",
    spec: "Cured Mahogany & Copper Suspensions",
  },
  {
    id: "modular-wooden-storage-unit-studio",
    product: "The Modular Storage System",
    price: "₦780,000",
    category: "custom",
    image: "/Modular_wooden_storage_unit_studio_202607131957.jpeg",
    spec: "Interlocking Walnut Components",
  },
  {
    id: "wooden-blanket-chest-studio",
    product: "The Heritage Blanket Chest",
    price: "₦340,000",
    category: "custom",
    image: "/Wooden_blanket_chest_studio_202607131956.jpeg",
    spec: "Solid cedar wood lined interior & Ash Exterior",
  },
  {
    id: "wooden-cable-management-box-studio",
    product: "The Cable Organizer Chest",
    price: "₦45,000",
    category: "custom",
    image: "/Wooden_cable_management_box_desk_202607131956.jpeg",
    spec: "Sleek Walnut Shell & Magnetic Lid",
  },
  {
    id: "wooden-chest-of-drawers-studio",
    product: "The Heritage Chest of Drawers",
    price: "₦540,000",
    category: "custom",
    image: "/Wooden_chest_of_drawers_studio_202607131956.jpeg",
    spec: "Cured Oak & Inset Steel Accents",
  },
  {
    id: "wooden-clothes-horse-studio",
    product: "The Wooden Clothes Horse",
    price: "₦90,000",
    category: "custom",
    image: "/Wooden_clothes_horse_studio_202607131957.jpeg",
    spec: "Solid Ash & Minimalist Pivot Hinges",
  },
  {
    id: "wooden-coat-rack-studio",
    product: "The Sculpted Coat Rack",
    price: "₦110,000",
    category: "custom",
    image: "/Wooden_coat_rack_studio_photography_202607131956.jpeg",
    spec: "Solid Ash & Aged Pewter Pegs",
  },
  {
    id: "wooden-coat-stand-studio",
    product: "The Atelier Coat Stand",
    price: "₦135,000",
    category: "custom",
    image: "/Wooden_coat_stand_in_studio_202607131956.jpeg",
    spec: "Rosewood Columns & Heavy Base Weight",
  },
  {
    id: "wooden-credenza-live-edge-studio",
    product: "The Live-Edge Buffet Credenza",
    price: "₦850,000",
    category: "custom",
    image: "/Wooden_credenza_with_live-edge_202607131957.jpeg",
    spec: "Bespoke Live-Edge Iroko & Steel Frame",
  },
  {
    id: "wooden-desk-clock-studio",
    product: "The Minimalist Desk Clock",
    price: "₦55,000",
    category: "custom",
    image: "/Wooden_desk_clock_studio_202607131956.jpeg",
    spec: "Turned Walnut Block & Brass Hands",
  },
  {
    id: "wooden-display-cabinet-studio",
    product: "The Glass Display Cabinet",
    price: "₦920,000",
    category: "custom",
    image: "/Wooden_display_cabinet_studio_ph_202607131957.jpeg",
    spec: "Slatted Oak Frame & Toughened Fluted Glass",
  },
  {
    id: "wooden-drafting-table-frame-studio",
    product: "The Drafting Table Frame",
    price: "₦380,000",
    category: "custom",
    image: "/Wooden_drafting_table_frame_studio_202607131956.jpeg",
    spec: "Heavy-duty Oak frame & Height Adjustment Gears",
  },
  {
    id: "wooden-drafting-table-studio",
    product: "The Architect Drafting Table",
    price: "₦650,000",
    category: "custom",
    image: "/Wooden_drafting_table_studio_202607131957.jpeg",
    spec: "Tiltable Oak Drafting Table & Built-in Ruler Rails",
  },
  {
    id: "wooden-floor-lamp-studio",
    product: "The Tripod Floor Lamp",
    price: "₦180,000",
    category: "custom",
    image: "/Wooden_floor_lamp_studio_202607131956.jpeg",
    spec: "Turned Walnut legs & Natural Oatmeal Shade",
  },
  {
    id: "wooden-jewelry-armoire-studio",
    product: "The Jewelry Armoire Cabinet",
    price: "₦460,000",
    category: "custom",
    image: "/Wooden_jewelry_armoire_studio_202607131957.jpeg",
    spec: "Velvet-lined drawers & Walnut Inset Shells",
  },
  {
    id: "wooden-jewelry-box-studio",
    product: "The Velvet-Lined Jewelry Box",
    price: "₦75,000",
    category: "custom",
    image: "/Wooden_jewelry_box_studio_202607131957.jpeg",
    spec: "Figured Walnut & Inset Gilded Corner Clasps",
  },
  {
    id: "wooden-ladder-quilt-rack-studio",
    product: "The Decorative Quilt Ladder",
    price: "₦85,000",
    category: "custom",
    image: "/Wooden_ladder_quilt_rack_studio_202607131956.jpeg",
    spec: "Sanded Oak & Floating Rungs",
  },
  {
    id: "wooden-pedestal-stand-studio",
    product: "The Gallery Pedestal Stand",
    price: "₦120,000",
    category: "custom",
    image: "/Wooden_pedestal_stand_studio_202607131956.jpeg",
    spec: "Solid Oak Block & Satin Matte Polish",
  },
  {
    id: "wooden-room-divider-modern-studio",
    product: "The Geometric Room Divider",
    price: "₦540,000",
    category: "custom",
    image: "/Wooden_room_divider_modern_studio_202607131956.jpeg",
    spec: "Architectural Screen & Custom Pivot Plates",
  },
  {
    id: "wooden-shelving-unit-side-table-studio",
    product: "The Modular Side Shelving Unit",
    price: "₦260,000",
    category: "custom",
    image: "/Wooden_shelving_unit_side_table_202607131956.jpeg",
    spec: "Three-tier Walnut shelves & Sturdy Steel Frames",
  },
  {
    id: "wooden-spiral-bookshelf-studio",
    product: "The Spiral Bookshelf",
    price: "₦680,000",
    category: "custom",
    image: "/Wooden_spiral_bookshelf_studio_202607131956.jpeg",
    spec: "Sculptural Spiral Column & Ashwood Panels",
  },
  {
    id: "wooden-step-stool-studio",
    product: "The Utility Step Stool",
    price: "₦65,000",
    category: "custom",
    image: "/Wooden_step_stool_studio_photogr_202607131957.jpeg",
    spec: "Sturdy Oak Steps & Ergonomic Grip Slot",
  },
  {
    id: "wooden-storage-bench-studio",
    product: "The Foyer Storage Bench",
    price: "₦380,000",
    category: "custom",
    image: "/Wooden_storage_bench_studio_202607131956.jpeg",
    spec: "Smoked Iroko & Inset Leather Storage Bin",
  },
  {
    id: "wooden-valet-stand-studio",
    product: "The Gentleman's Valet Stand",
    price: "₦195,000",
    category: "custom",
    image: "/Wooden_valet_stand_studio_202607131956.jpeg",
    spec: "Turned Mahogany with Trouser Hanger & Coin Tray",
  },
  {
    id: "wooden-vanity-desk-studio",
    product: "The Custom Vanity Desk",
    price: "₦720,000",
    category: "custom",
    image: "/Wooden_vanity_desk_studio_202607131957.jpeg",
    spec: "Oak vanity drawer desk & integrated mirror frame",
  },
  {
    id: "wooden-wall-mounted-shelf-studio",
    product: "The Wall-Mounted Shelf",
    price: "₦80,000",
    category: "custom",
    image: "/Wooden_wall-mounted_shelf_studio_202607131956.jpeg",
    spec: "Floating Ash shelf & hidden mounting brackets",
  },
  {
    id: "wooden-wall-clock-studio-1",
    product: "The Sculpted Wall Clock",
    price: "₦95,000",
    category: "custom",
    image: "/Wooden_wall_clock_studio_202607131956.jpeg",
    spec: "Solid Oak Radial cut & Polished Copper Hands",
  },
  {
    id: "wooden-wall-clock-studio-2",
    product: "The Heritage Wall Clock",
    price: "₦95,000",
    category: "custom",
    image: "/Wooden_wall_clock_studio_photogr_202607131956.jpeg",
    spec: "Walnut grain dial & Minimalist marker lines",
  },
  {
    id: "wooden-wastebasket-studio",
    product: "The Wooden Wastebasket",
    price: "₦40,000",
    category: "custom",
    image: "/Wooden_wastebasket_in_studio_202607131956.jpeg",
    spec: "Molded Birch Shell & Satin finish",
  },
  {
    id: "wooden-whiteboard-frame-studio",
    product: "The Studio Whiteboard Frame",
    price: "₦180,000",
    category: "custom",
    image: "/Wooden_whiteboard_frame_studio_202607131956.jpeg",
    spec: "Mahogany outer frame & integrated pen tray",
  },
  // UNSPLASH CUSTOM (6 ITEMS)
  {
    id: "lumina-bench-unsplash",
    product: "The Lumina Bench",
    price: "₦470,000",
    category: "custom",
    image: "https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=800",
    spec: "Raw Concrete & Walnut Top Surface",
  },
  {
    id: "apex-bench-unsplash",
    product: "The Apex Bench",
    price: "₦226,000",
    category: "custom",
    image: "https://images.unsplash.com/photo-1595515106967-4224bb4ebd4e?q=80&w=800",
    spec: "Burl Wood & Brushed Bronze Base",
  },
  {
    id: "oak-sideboard-unsplash-extra-1",
    product: "The Grand Fluted Sideboard",
    price: "₦940,000",
    category: "custom",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800",
    spec: "Architectural fluted Oak sideboard with custom bronze feet",
  },
  {
    id: "minimalist-meeting-unsplash-extra",
    product: "The Summit Office Boardroom Table",
    price: "₦1,980,000",
    category: "custom",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800",
    spec: "Extra-long custom oak panel table with under-surface cord routing",
  },
  {
    id: "workspace-desk-setup-unsplash-extra",
    product: "The Minimalist Credenza Desk",
    price: "₦680,000",
    category: "custom",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=800",
    spec: "Solid block wooden desk with integrated cabinet drawer units",
  },
  {
    id: "cathedral-dining-room-unsplash-extra",
    product: "The Stockholm Modular Cabinet",
    price: "₦1,150,000",
    category: "custom",
    image: "https://images.unsplash.com/photo-1604578762246-411356547ec1?q=80&w=800",
    spec: "Multi-shelf display console with safety tempered glass doors",
  },
];

export const MATERIALS: Material[] = [
  {
    name: "Calacatta Marble",
    origin: "Imported, Lagos Port",
    image: "https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=800",
  },
  {
    name: "Aso-Oke Weave Linen",
    origin: "Handwoven, Iseyin",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?q=80&w=800",
  },
  {
    name: "Smoked Black Walnut",
    origin: "Bespoke Cured, Lagos",
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=800",
  },
  {
    name: "Aged Brushed Brass",
    origin: "Kano Metalworks, Nigeria",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800",
  },
  {
    name: "Cordovan Leather",
    origin: "Tanneries, Kano",
    image: "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?q=80&w=800",
  },
  {
    name: "Hand Poured Concrete",
    origin: "Lagos Casting Yard",
    image: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=800",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: "The bespoke conference table from Vision Worth is the absolute centrepiece of our Ikoyi boardroom. Every client who walks in comments on its raw texture and quiet strength.",
    author: "Chidinma Okafor",
    title: "Architect, Lagos",
  },
  {
    quote: "We wanted furniture that represented contemporary Nigeria without leaning into stereotypes. Vision Worth delivered pieces that are global in standard, local in heart.",
    author: "Akintoye Davidson",
    title: "CEO, Davidson & Co, Ikoyi",
  },
  {
    quote: "The attention to wood grain alignment, seamless joints, and tactile finish is unmatched. Vision Worth is the best-kept secret in Nigerian luxury.",
    author: "Yejide Alabi",
    title: "Interior Designer, Lekki",
  },
];

export const EDITORIAL_IMAGES = [
  {
    url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200",
    location: "Private Residence, Ikoyi",
  },
  {
    url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=800",
    location: "Master Bedroom, Victoria Island",
  },
  {
    url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=800",
    location: "Showroom Study, Lagos",
  },
  {
    url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800",
    location: "Atelier Suite, Lekki",
  },
  {
    url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800",
    location: "Bespoke Suite, Port Harcourt",
  },
  {
    url: "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?q=80&w=800",
    location: "Penthouse Lounge, Abuja",
  },
];
